"""Verify the Sharadar local archive and write the SAFE-TO-CANCEL manifest
(reports/sharadar_full_archive.md). Uses DuckDB to query the parquet files (row counts, date
coverage, distinct keys) plus real-value spot-checks that the data is genuine, not a truncated error.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import duckdb

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

REPO = Path(__file__).resolve().parents[1]
ARCHIVE = REPO / "data_archive"
PQ = ARCHIVE / "sharadar_parquet"

# table -> (date column or None, key column or None, one-line description, future idea it supports)
META = {
    "SF1": ("datekey", "ticker", "Core US Fundamentals (point-in-time)", "valuation/quality/fund-momentum features"),
    "SF2": ("filingdate", "ticker", "Core US Insiders (Form 3/4/5 transactions)", "insider-cluster signal"),
    "SF3": ("calendardate", "investorname", "Core US Institutional Investors (13F holdings)", "institutional-ownership signals"),
    "SF3A": ("calendardate", "ticker", "13F aggregated by issuer/security", "ownership breadth per name"),
    "SF3B": ("calendardate", "investorname", "13F aggregated by investor", "investor-level positioning"),
    "SEP": ("date", "ticker", "Equity Prices (delisted-inclusive)", "prices / returns / liquidity"),
    "SFP": ("date", "ticker", "Fund & ETF Prices", "self-contained benchmarks (IWM/SPY)"),
    "DAILY": ("date", "ticker", "Daily Metrics: marketcap, EV, P/E, P/B, P/S, EV/EBITDA", "fast precomputed valuations"),
    "ACTIONS": ("date", "ticker", "Corporate Actions (splits/divs/delistings/bankruptcy)", "delisting-aware returns"),
    "EVENTS": ("date", "ticker", "Corporate Events incl. announcement/event dates", "PEAD earnings-date precision"),
    "SP500": ("date", "ticker", "S&P 500 historical constituents", "point-in-time index membership"),
    "TICKERS": (None, "ticker", "Ticker metadata (sector/SIC/delisted flags)", "universe scope + reference"),
    "INDICATORS": (None, "indicator", "DATA DICTIONARY — definition of every column", "interpreting all tables after access ends"),
}


def q(sql):
    return duckdb.sql(sql).fetchall()


def stats(short, datecol, keycol):
    p = (PQ / f"{short}.parquet").as_posix()
    rows = q(f"SELECT COUNT(*) FROM read_parquet('{p}')")[0][0]
    dmin = dmax = None
    if datecol:
        try:
            dmin, dmax = q(f"SELECT MIN({datecol}), MAX({datecol}) FROM read_parquet('{p}')")[0]
        except Exception:
            pass
    ndist = None
    if keycol:
        try:
            ndist = q(f"SELECT COUNT(DISTINCT {keycol}) FROM read_parquet('{p}')")[0][0]
        except Exception:
            pass
    return rows, dmin, dmax, ndist


def spot_checks():
    out = []
    sep = (PQ / "SEP.parquet").as_posix()
    r = q(f"SELECT close FROM read_parquet('{sep}') WHERE ticker='AAPL' AND date='2020-12-31'")
    out.append(("SEP AAPL close 2020-12-31", f"{r[0][0]:.2f}" if r else "MISSING", "≈132 split-adj"))
    daily = (PQ / "DAILY.parquet").as_posix()
    r = q(f"SELECT marketcap FROM read_parquet('{daily}') WHERE ticker='AAPL' AND date='2020-12-31'")
    out.append(("DAILY AAPL marketcap 2020-12-31 ($B)", f"{r[0][0]/1e3:.0f}" if r else "MISSING", "≈2255 ($2.25T)"))
    sf2 = (PQ / "SF2.parquet").as_posix()
    r = q(f"SELECT COUNT(*), MIN(filingdate), MAX(filingdate) FROM read_parquet('{sf2}') WHERE ticker='AAPL'")
    out.append(("SF2 AAPL insider filings", f"{r[0][0]:,} ({r[0][1]}..{r[0][2]})" if r else "MISSING", ">0 rows"))
    sf3 = (PQ / "SF3.parquet").as_posix()
    r = q(f"SELECT COUNT(DISTINCT investorname) FROM read_parquet('{sf3}')")
    out.append(("SF3 distinct institutional investors", f"{r[0][0]:,}" if r else "MISSING", ">1000"))
    return out


def main():
    rows_by_table = {}
    total_bytes = sum(f.stat().st_size for f in ARCHIVE.rglob("*") if f.is_file())
    lines = ["# Sharadar local archive — manifest & SAFE-TO-CANCEL verdict\n"]
    lines.append(f"_Archive base: `data_archive/` (local, non-cloud). Total on disk: "
                 f"**{total_bytes/1e9:.2f} GB**. Generated by scripts/verify_archive.py._\n")

    lines.append("## Tables\n")
    lines.append("| Table | Rows | Date coverage | Distinct key | Parquet | Raw | Status |")
    lines.append("|---|---|---|---|---|---|---|")
    all_ok = True
    for short, (dc, kc, _desc, _idea) in META.items():
        pqf = PQ / f"{short}.parquet"
        prov_f = PQ / f"{short}.provenance.json"
        prov = json.loads(prov_f.read_text()) if prov_f.exists() else {}
        if not pqf.exists():
            lines.append(f"| {short} | — | — | — | MISSING | — | **MISSING** |")
            all_ok = False
            continue
        rows, dmin, dmax, ndist = stats(short, dc, kc)
        rows_by_table[short] = rows
        raw_gb = (prov.get("raw_bytes") or 0) / 1e9
        pq_gb = pqf.stat().st_size / 1e9
        cov = f"{dmin}..{dmax}" if dmin is not None else "—"
        raw_cell = f"{raw_gb:.2f} GB" if raw_gb else "(parquet-only)"
        ok = rows and rows > 0
        all_ok = all_ok and ok
        lines.append(f"| {short} | {rows:,} | {cov} | {ndist if ndist is not None else '—'} | "
                     f"{pq_gb:.2f} GB | {raw_cell} | {'complete' if ok else 'EMPTY'} |")

    lines.append("\n## Spot-checks (data is real, not a truncated error)\n")
    lines.append("| Check | Value | Expected |\n|---|---|---|")
    sc_ok = True
    for name, val, exp in spot_checks():
        lines.append(f"| {name} | {val} | {exp} |")
        if val == "MISSING":
            sc_ok = False

    safe = all_ok and sc_ok
    lines.append(f"\n## VERDICT: {'**SAFE TO CANCEL — TRUE**' if safe else '**NOT SAFE TO CANCEL**'}\n")
    if safe:
        lines.append("Every entitled bundle table is present, non-empty, parses cleanly, and spot-checks "
                     "return real values. The local archive is complete and self-contained. Cancelling "
                     "Nasdaq Data Link stops API pulls but does NOT touch these local files — they remain "
                     "fully usable forever.\n")
    else:
        lines.append("One or more tables are missing/empty or a spot-check failed. Do NOT cancel; re-run "
                     "`scripts/archive_sharadar.py` (resumable) for the affected tables first.\n")

    lines.append("## What each table is / what it unlocks\n")
    for short, (_dc, _kc, desc, idea) in META.items():
        lines.append(f"- **{short}** — {desc}. → *{idea}*.")
    lines.append("\n**Data dictionary:** `data_archive/sharadar_parquet/INDICATORS.parquet` defines every "
                 "column of every table (table, indicator, title, description) — the key to interpreting "
                 "the archive after access ends.\n")

    lines.append("## Provenance\n")
    lines.append("Per-table `data_archive/sharadar_parquet/<TABLE>.provenance.json`: download timestamp, "
                 "endpoint (Nasdaq Data Link datatables bulk export), source method, nasdaq-data-link "
                 "client version, row count, byte sizes. Raw source-of-truth zips under "
                 "`data_archive/sharadar_raw/<TABLE>/`. SF1 & SEP were already cached complete — their "
                 "parquet was archived and the multi-GB raw re-pull skipped per instruction (raw can be "
                 "re-pulled while the subscription is live if a raw source-of-truth is later wanted).\n")

    lines.append("## Cancellation checklist (run before you cancel Nasdaq Data Link)\n")
    lines.append(f"1. ☐ This manifest says **SAFE TO CANCEL — {'TRUE' if safe else 'FALSE'}** (above).")
    lines.append(f"2. ☐ Total archive size is sane (**{total_bytes/1e9:.2f} GB**) and on **local disk** "
                 "(`data_archive/`, NOT under `C:\\Users\\josep\\OneDrive`).")
    lines.append("3. ☐ **Raw exports exist** (not just parquet): list `data_archive/sharadar_raw/*/*.zip` "
                 "— every pulled table has its source-of-truth zip.")
    lines.append("4. ☐ Note: **SF1 & SEP are parquet-only** (raw re-pull skipped per your directive). If "
                 "you want their raw zips too, re-pull them **before** cancelling (optional).")
    lines.append("5. ☐ **BACK UP `data_archive/` to a second location** (external drive / another disk). "
                 "It is gitignored — NOT on GitHub — so this is the ONLY copy, and after cancelling it "
                 "**cannot be re-downloaded**. A single-disk copy of un-reproducible licensed data is a risk.")
    lines.append("6. ☐ Reminder: cancelling stops **API pulls only**. These local files remain **fully "
                 "usable forever** — every future idea (PEAD, insider clusters, institutional signals, "
                 "benchmarks) runs off this archive with no re-subscription.\n")

    (REPO / "reports" / "sharadar_full_archive.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"Archive total: {total_bytes/1e9:.2f} GB")
    print("Rows:", {k: f"{v:,}" for k, v in rows_by_table.items()})
    print("SAFE TO CANCEL:", safe)
    print("Wrote reports/sharadar_full_archive.md")


if __name__ == "__main__":
    main()
